

#  Making a function to find the average of the list........
def Average(lst):

    #  Dividing the sum of list to the length of list using built in functions.........
    return sum(lst) / len(lst)

    #  the list is as follows.......
my_list = [1, 22, 32, 12, 55, 88, 76, 54, 2, 1, 22, 33, 44, 5, 6, 6, 7, 5, 0]

#          Calling a function................
average = Average(my_list)
#       Rounding off the average and printing it..........
print(round(average, 2))
